<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="DTO\" />
    <Folder Include="InterFaces\" />
    <Folder Include="Services\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\BrainHope.DataAcess\BrainHope.DataAcess.csproj" />
    <ProjectReference Include="..\Utilites\Utilites.csproj" />
  </ItemGroup>

</Project>
